version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:3.9
    container_name: zookeeper
    ports:
      - "2181:2181"  # 映射 Zookeeper 客户端端口到主机
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"  # 允许匿名登录
    volumes:
      - ./zookeeper-data:/bitnami/zookeeper  # 挂载 Zookeeper 数据目录到当前目录下的 zookeeper-data
    networks:
      - kafka-net

  kafka1:
    image: bitnami/kafka:3.4
    container_name: kafka1
    ports:
      - "9092:9092"  # 映射 Kafka Broker 端口到主机
    environment:
      KAFKA_CFG_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181  # 连接 Zookeeper
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092"
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"  # 允许明文监听器
    volumes:
      - ./kafka1-data:/bitnami/kafka  # 挂载 Kafka 数据目录到当前目录下的 kafka1-data
    depends_on:
      - zookeeper
    networks:
      - kafka-net

  kafka2:
    image: bitnami/kafka:3.4
    container_name: kafka2
    ports:
      - "9093:9092"  # 映射 Kafka Broker 端口到主机
    environment:
      KAFKA_CFG_BROKER_ID: 2
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092"
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
    volumes:
      - ./kafka2-data:/bitnami/kafka  # 挂载 Kafka 数据目录到当前目录下的 kafka2-data
    depends_on:
      - zookeeper
    networks:
      - kafka-net

  kafka3:
    image: bitnami/kafka:3.4
    container_name: kafka3
    ports:
      - "9094:9092"  # 映射 Kafka Broker 端口到主机
    environment:
      KAFKA_CFG_BROKER_ID: 3
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092"
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
    volumes:
      - ./kafka3-data:/bitnami/kafka  # 挂载 Kafka 数据目录到当前目录下的 kafka3-data
    depends_on:
      - zookeeper
    networks:
      - kafka-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: "local-kafka"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka1:9092,kafka2:9092,kafka3:9092"
      KAFKA_CLUSTERS_0_ZOOKEEPER: "zookeeper:2181"
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    networks:
      - kafka-net

networks:
  kafka-net:
    name: kafka-net 
    driver: bridge
