server {
    listen 80;
    server_name proxy-header.tnginx.org;

    location / {

        proxy_pass http://192.168.60.155:8091;


        # proxy_pass_request_headers off;
  
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_connect_timeout 5s;
        proxy_read_timeout 60s;
        
        # 如果要排查 HEAD 请求，确保 Nginx 不会缓存响应
        proxy_cache off;
    }

    # 开启 Nginx 错误日志，级别设为 debug 可以看到更详细的 Header 交换过程
    # error_log /var/log/nginx/error.log debug;
    # access_log /var/log/nginx/access.log;
}