global:
  scrape_interval:     60s
  evaluation_interval: 60s
  external_labels:
    monitor: 'prometheus-gather'
 
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

rule_files:
   - "first_rules/*.yml"

scrape_configs:
  - job_name: "prometheus-gather"
    static_configs:
      - targets:
        - 192.168.3.97:9090
        - 192.168.3.97:9091
        - 192.168.3.97:3000
       # - pushgateway:9091
       # - grafana:3000
                  
#  - job_name: pushgateway
#    static_configs:
#      - targets:
#        - pushgateway:9091
#        labels:
#          instance: pushgateway
#
#  - job_name: grafana
#    static_configs:
#      - targets:
#        - grafana:3000
#        labels:
#          instance: grafana
