version: "3"

networks:
  default:
#    external:
    name: prom

services:
  pushgateway:
    container_name: pushgateway
    image: prom/pushgateway:${PUSHGATEWAY_VERSION}
    ports:
      - 9091:9091
    restart: always
